Unable to use unit test domain class mocks due to 'java.lang.NoClassDefFoundError: grails/gorm/TestCriteriaBuilder' error, changing to integration spec